# This is an example config file
# You should duplicate this file and rename it in the same directory
# Change all relevant fields before running the bot for the first time

ip = "127.0.0.1"
port = 25575
password = ""
timeout_duration = 3
discord_bot_token = "token_here"
embed_footer = "@PalCONBot"
embed_thumbnail = "https://media.discordapp.net/attachments/631249406775132182/1201307493163335680/relaxasarus.png?ex=65c957c9&is=65b6e2c9&hm=e0a820d7130239e6ef16b6bd5ec86bdc1976c63740aaccc842ba19c29f85ecf2&=&format=webp&quality=lossless"
generic_bot_error = "Unable to process your request"

# --- Set the below features to 'true' to enable. 'false' to disable. ---
# - Check palword's current IP address when using /status?
check_public_ip = false
# - Check palword's CPU usage when using /status?
check_cpu = false
# - Check palword's available RAM when using /status?
check_ram = false
# --- End /status features. ---

# PalCON bot and Palworld Server must be on the same IP for this to work properly.
# - Warning: On mismatch, exposes the PalCON bot's current IP address to discord.
# - If check_public_ip is false, this value is not needed.
expected_public_ip = ""

# Emojis used for the /status description.
# Default emojis work anywhere. Can be replaced with custom emojis.
# PalCON must be in the server that any custom emojis belong to.
embed_pass_emoji = ":white_check_mark:"
embed_fail_emoji = ":no_entry:"
embed_unknown_emoji = ":grey_question:"